apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaafardialloo/ArgoCDAppConfig_GitOps.git
    targetRevision: HEAD
    path:
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
