apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-argo-guestbook
spec:
  selector:
    matchLabels:
      app: my-argo-guestbook
  replicas: 2
  template:
    metadata:
      labels:
        app: my-argo-guestbook
    spec:
      containers:
        - name: myapp
          image: nanajanashia/argocd-app:1.2
          ports:
            - containerPort: 8080